Prepare new version of theme 'lshostel2' for LS AAI
CESNET/lshostel-aai-proxy-idp-template pull request #6
Opened 2021-07-15 06:47 UTC by vyskocilpavel

* !This version cannot be deployed to BBMRI LS Hostel

2021-07-28 08:25 UTC, BaranekD requested changes
Just found some places where code style could be improved, functionality is OK for me.

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/consent/consentform.php
> +*/
You probably forgot to remove it.

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/consent/consentform.php
> +        array(
It's probably better to use a short array syntax.

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/consent/consentform.php
> +if ($this->data['sppp'] !== false) {
What are possible values for `$this->data['sppp']`? If it's just true/false, you can write just `if ($this->data['sppp'])`, otherwise it's ok.

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/consent/consentform.php
> +                // we hawe several values
typo (hawe x have)

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/consent/consentform.php
> +                // we hawe only one value
typo (hawe x have)

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/consent/consentform.php
> +	            </label>
Looks like the label tag has a wrong indentation

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/core/loginuserpass.php
> +    $hookinfo = array(
You can use short array syntax here as well.

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/core/loginuserpass.php
> +<!--                        </a>-->
Is it ok to leave this comment here or you just forgot to delete it?

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/default/includes/header.php
> +	$hookinfo = array(
You can use short array syntax.

2021-07-28 08:25 UTC, BaranekD commented on themes/lshostel2/default/post.php
> +</html>
Missing newline.

2022-02-07 07:59 UTC, dBucik commented
This PR has been extracted into creating a separate template.

2022-02-07 07:59 UTC, closed without merging